# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Downloads/Sample-Ui_V2/profile.ui'
#
# Created: Mon Apr 25 20:16:23 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 299)
        self.name_label = QtGui.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(20, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color:black;")
        self.name_label.setObjectName("name_label")
        self.header_label = QtGui.QLabel(Form)
        self.header_label.setStyleSheet("color:white;background-color:#121317;")
        self.header_label.setGeometry(QtCore.QRect(20, 20, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(40)
        font.setWeight(75)
        font.setBold(True)
        self.header_label.setFont(font)
        self.header_label.setFrameShape(QtGui.QFrame.Box)
        self.header_label.setObjectName("header_label")
        self.email_label = QtGui.QLabel(Form)
        self.email_label.setStyleSheet("color:black;")
        self.email_label.setGeometry(QtCore.QRect(20, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.phone_label = QtGui.QLabel(Form)
        self.phone_label.setStyleSheet("color:black;")
        self.phone_label.setGeometry(QtCore.QRect(20, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.nametag = QtGui.QLabel(Form)
        self.nametag.setStyleSheet("color:white;")
        self.nametag.setGeometry(QtCore.QRect(120, 100, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.nametag.setFont(font)
        self.nametag.setStyleSheet("color:white;")
        self.nametag.setObjectName("nametag")
        self.emailtag = QtGui.QLabel(Form)
        self.emailtag.setStyleSheet("color:white;")
        self.emailtag.setGeometry(QtCore.QRect(90, 140, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.emailtag.setFont(font)
        self.emailtag.setObjectName("emailtag")
        self.phonetag = QtGui.QLabel(Form)
        self.phonetag.setGeometry(QtCore.QRect(120, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.phonetag.setFont(font)
        self.phonetag.setObjectName("phonetag")
        self.phonetag.setStyleSheet("color:white;")
        self.position_label = QtGui.QLabel(Form)
        self.position_label.setStyleSheet("color:black;")
        self.position_label.setGeometry(QtCore.QRect(20, 222, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.position_label.setFont(font)
        self.position_label.setObjectName("position_label")
        self.dep_label = QtGui.QLabel(Form)
        self.dep_label.setGeometry(QtCore.QRect(20, 260, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.dep_label.setFont(font)
        self.dep_label.setStyleSheet("color:black;")
        self.dep_label.setObjectName("dep_label")
        self.postag = QtGui.QLabel(Form)
        self.postag.setGeometry(QtCore.QRect(110, 210, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.postag.setFont(font)
        self.postag.setObjectName("postag")
        self.postag.setStyleSheet("color:white;")
        self.deptag = QtGui.QLabel(Form)
        self.deptag.setStyleSheet("color:white;")
        self.deptag.setGeometry(QtCore.QRect(140, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.deptag.setFont(font)
        self.deptag.setObjectName("deptag")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label.setText(QtGui.QApplication.translate("Form", "Full name:", None, QtGui.QApplication.UnicodeUTF8))
        self.header_label.setText(QtGui.QApplication.translate("Form", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.email_label.setText(QtGui.QApplication.translate("Form", "E-mail:", None, QtGui.QApplication.UnicodeUTF8))
        self.phone_label.setText(QtGui.QApplication.translate("Form", "Phone No:", None, QtGui.QApplication.UnicodeUTF8))
        self.nametag.setText(QtGui.QApplication.translate("Form", "First Last", None, QtGui.QApplication.UnicodeUTF8))
        self.emailtag.setText(QtGui.QApplication.translate("Form", "someone@someone.com", None, QtGui.QApplication.UnicodeUTF8))
        self.phonetag.setText(QtGui.QApplication.translate("Form", "000", None, QtGui.QApplication.UnicodeUTF8))
        self.position_label.setText(QtGui.QApplication.translate("Form", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_label.setText(QtGui.QApplication.translate("Form", "Department:", None, QtGui.QApplication.UnicodeUTF8))
        self.postag.setText(QtGui.QApplication.translate("Form", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.deptag.setText(QtGui.QApplication.translate("Form", "department", None, QtGui.QApplication.UnicodeUTF8))

