# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Downloads/Sample-Ui_V2/profile.ui'
#
# Created: Mon Apr 25 20:16:23 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

import PyQt5.QtCore as QtCore
import PyQt5.QtGui as QtGui
import PyQt5.QtWidgets as QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 299)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(20, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color:black;")
        self.name_label.setObjectName("name_label")
        self.header_label = QtWidgets.QLabel(Form)
        self.header_label.setStyleSheet("color:white;background-color:#121317;")
        self.header_label.setGeometry(QtCore.QRect(20, 20, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(40)
        font.setWeight(75)
        font.setBold(True)
        self.header_label.setFont(font)
        self.header_label.setFrameShape(QtWidgets.QFrame.Box)
        self.header_label.setObjectName("header_label")
        self.email_label = QtWidgets.QLabel(Form)
        self.email_label.setStyleSheet("color:black;")
        self.email_label.setGeometry(QtCore.QRect(20, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.phone_label = QtWidgets.QLabel(Form)
        self.phone_label.setStyleSheet("color:black;")
        self.phone_label.setGeometry(QtCore.QRect(20, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.nametag = QtWidgets.QLabel(Form)
        self.nametag.setStyleSheet("color:white;")
        self.nametag.setGeometry(QtCore.QRect(120, 100, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.nametag.setFont(font)
        self.nametag.setStyleSheet("color:white;")
        self.nametag.setObjectName("nametag")
        self.emailtag = QtWidgets.QLabel(Form)
        self.emailtag.setStyleSheet("color:white;")
        self.emailtag.setGeometry(QtCore.QRect(90, 140, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.emailtag.setFont(font)
        self.emailtag.setObjectName("emailtag")
        self.phonetag = QtWidgets.QLabel(Form)
        self.phonetag.setGeometry(QtCore.QRect(120, 180, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.phonetag.setFont(font)
        self.phonetag.setObjectName("phonetag")
        self.phonetag.setStyleSheet("color:white;")
        self.position_label = QtWidgets.QLabel(Form)
        self.position_label.setStyleSheet("color:black;")
        self.position_label.setGeometry(QtCore.QRect(20, 222, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.position_label.setFont(font)
        self.position_label.setObjectName("position_label")
        self.dep_label = QtWidgets.QLabel(Form)
        self.dep_label.setGeometry(QtCore.QRect(20, 260, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.dep_label.setFont(font)
        self.dep_label.setStyleSheet("color:black;")
        self.dep_label.setObjectName("dep_label")
        self.postag = QtWidgets.QLabel(Form)
        self.postag.setGeometry(QtCore.QRect(110, 210, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.postag.setFont(font)
        self.postag.setObjectName("postag")
        self.postag.setStyleSheet("color:white;")
        self.deptag = QtWidgets.QLabel(Form)
        self.deptag.setStyleSheet("color:white;")
        self.deptag.setGeometry(QtCore.QRect(140, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.deptag.setFont(font)
        self.deptag.setObjectName("deptag")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_label.setText(_translate("Form", "Full name:"))
        self.header_label.setText(_translate("Form", "Name"))
        self.email_label.setText(_translate("Form", "E-mail:"))
        self.phone_label.setText(_translate("Form", "Phone No:"))
        self.nametag.setText(_translate("Form", "First Last"))
        self.emailtag.setText(_translate("Form", "someone@someone.com"))
        self.phonetag.setText(_translate("Form", "000"))
        self.position_label.setText(_translate("Form", "Position:"))
        self.dep_label.setText(_translate("Form", "Department:"))
        self.postag.setText(_translate("Form", "position"))
        self.deptag.setText(_translate("Form", "department"))