
import sys

from connector import *
from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 10, 441, 471))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.user_entry = QtGui.QLineEdit(self.widget)
        self.user_entry.setObjectName("user_entry")
        self.horizontalLayout.addWidget(self.user_entry)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.pass_entry = QtGui.QLineEdit(self.widget)
        self.pass_entry.setObjectName("pass_entry")
        self.horizontalLayout_2.addWidget(self.pass_entry)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.fname_entry = QtGui.QLineEdit(self.widget)
        self.fname_entry.setText("")
        self.fname_entry.setObjectName("fname_entry")
        self.horizontalLayout_3.addWidget(self.fname_entry)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lname_entry = QtGui.QLineEdit(self.widget)
        self.lname_entry.setObjectName("lname_entry")
        self.horizontalLayout_4.addWidget(self.lname_entry)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.email = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        self.horizontalLayout_5.addWidget(self.email)
        self.email_entry = QtGui.QLineEdit(self.widget)
        self.email_entry.setText("")
        self.email_entry.setObjectName("email_entry")
        self.horizontalLayout_5.addWidget(self.email_entry)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.phone = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.phone.setFont(font)
        self.phone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phone.setAlignment(QtCore.Qt.AlignCenter)
        self.phone.setObjectName("phone")
        self.horizontalLayout_6.addWidget(self.phone)
        self.phone_entry = QtGui.QLineEdit(self.widget)
        self.phone_entry.setText("")
        self.phone_entry.setObjectName("phone_entry")
        self.horizontalLayout_6.addWidget(self.phone_entry)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.register_2 = QtGui.QPushButton(self.widget)
        self.register_2.clicked.connect(self.doRegister)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.register_2.setFont(font)
        self.register_2.setObjectName("register_2")
        self.verticalLayout.addWidget(self.register_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("Form", "Register User", None, QtGui.QApplication.UnicodeUTF8))
        self.username.setText(QtGui.QApplication.translate("Form", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.password.setText(QtGui.QApplication.translate("Form", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.name.setText(QtGui.QApplication.translate("Form", "Firstname", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Lastname", None, QtGui.QApplication.UnicodeUTF8))
        self.email.setText(QtGui.QApplication.translate("Form", "E-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.phone.setText(QtGui.QApplication.translate("Form", "Phone No.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.register_2.setText(QtGui.QApplication.translate("Form", "Confirm", None, QtGui.QApplication.UnicodeUTF8))

    def doRegister(self):
        user = self.user_entry.text()
        pas = self.pass_entry.text()
        first = self.fname_entry.text()
        last = self.lname_entry.text()
        mail = self.email_entry.text()
        phone = self.phone_entry.text()
        data = {'username': user, 'password': pas, 'first_name': first,
                'last_name': last, 'email': mail, 'phone': phone}
        url = "Somchai/register"
        connector = Connector()
        connector.post(url, data)


def main():

    app = QtGui.QApplication(sys.argv)
    w = QtGui.QWidget()
    ex = Ui_Form()
    ex.setupUi(w)
    w.show()
    return app.exec_()


if __name__ == '__main__':
    sys.exit(main())